name: "OCI Image Builder"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom tag'
        default: 'latest'

env: 
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.event.inputs.tag || 'latest' }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        component: [webapp, backend]
        include:
          - component: webapp
            context: ./found-webapp
            image_suffix: webapp
          - component: backend
            context: ./backend
            image_suffix: backend

    steps:
      - uses: actions/checkout@v6
    
      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Image Name
        id: prep
        run: |
          # Convertimos todo a minúsculas para cumplir con GHCR [cite: 37, 42]
          REPO_LOWER="${GITHUB_REPOSITORY,,}"
          echo "full_image_name=${{ env.REGISTRY }}/${REPO_LOWER}-${{ matrix.image_suffix }}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.context }}
          push: true
          # ${{ steps.prep.outputs.full_image_name }}:${{ env.IMAGE_TAG }}
          tags: |
            ${{ steps.prep.outputs.full_image_name }}:beta-${{ github.run_id }}
            ${{ steps.prep.outputs.full_image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max